In [120]:
import numpy as np
import pandas as pd

In [121]:
with open('input4', 'r') as f:
    lines = [l.strip() for l in f.readlines()]

## Part 1

In [118]:
lines = [
    '7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1',
    '',
    '22 13 17 11  0',
    ' 8  2 23  4 24',
    '21  9 14 16  7',
    ' 6 10  3 18  5',
    ' 1 12 20 15 19',
    '',
    ' 3 15  0  2 22',
    ' 9 18 13 17  5',
    '19  8  7 25 23',
    '20 11 10 24  4',
    '14 21 16 12  6',
    '',
    '14 21 17 24  4',
    '10 16 15  9 19',
    '18  8 23 26 20',
    '22 11 13  6  5',
    ' 2  0 12  3  7',
]

In [122]:
marked_numbers = [int(n) for n in lines[0].split(',')]
boards = []
for line in lines[1:]:
    if len(line) == 0:
        current_board = np.zeros((5, 5))
        board_index = 0
    else:
        current_board[board_index, :] = [int(n) for n in line.split()]
        board_index += 1
        if board_index == 5:
            boards.append(current_board.reshape(1, 5, 5))
boards = np.concatenate(boards)

In [94]:
for num in marked_numbers:
    boards[boards == num] = -1
    col_sums = boards.sum(axis=1)
    row_sums = boards.sum(axis=2)
    win_index, _ = np.where(row_sums == -5)
    if len(win_index) > 0:
        win_board = boards[win_index[0], :, :]
        win_board[win_board == -1] = 0
        print(win_index[0], int(win_board.sum()), num, num * int(win_board.sum()))
        print(boards[win_index[0], :, :])
        break
    win_index, _ = np.where(col_sums == -5)
    if len(win_index) > 0:
        win_board = boards[win_index[0], :, :]
        win_board[win_board == -1] = 0
        print(win_index[0], int(win_board.sum()), num, num * int(win_board.sum()))
        print(boards[win_index[0], :, :])
        break

85 766 95 72770
[[55. 15. 85. 39.  4.]
 [ 0.  0.  0.  0.  0.]
 [ 0. 47. 61.  9. 66.]
 [82. 32.  0.  0. 16.]
 [50. 96. 14. 60. 35.]]


## Part 2

In [123]:
winners = []
for num in marked_numbers:
    boards[boards == num] = -1
    col_sums = boards.sum(axis=1)
    row_sums = boards.sum(axis=2)
    win_index, _ = np.where(row_sums == -5)
    for w in win_index:
        if w not in winners:
            winners.append(w)
    win_index, _ = np.where(col_sums == -5)
    for w in win_index:
        if w not in winners:
            winners.append(w)
    if len(winners) == boards.shape[0]:
        win_board = boards[winners[-1], :, :]
        win_board[win_board == -1] = 0
        print(winners[-1], int(win_board.sum()), num, num * int(win_board.sum()))
        break

75 296 47 13912
